### ISSUE TITLE
Proxy error on our react dev server

### ISSUE THREAD

**Issue by dmndc** [dm9-travel/travel-app#28]
The issue that I get when I run npm start:

Proxy error: Could not proxy request /api/getAirport?lat=32.7778346&long=-96.7955549 from localhost:3000 to http://localhost:3001.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

**Comment by jsjutzi** [comment]
I assume this isn't relevant anymore :)
